---
- hosts: jenkins
  become: true
  tasks:
    
    -  name: Add slave node through a BASH script
       ansible.builtin.shell: add-jenkins-slave.sh "{{ nodename }}" "{{ credid }}" "{{ label }}"
       args:
         chdir: /shared/jenkins/