---
- hosts: jenkins
  become: true
  tasks:
    
    -  name: Add slave node through a BASH script
       ansible.builtin.shell:
         cmd: bash /shared/jenkins/add-jenkins-slave.sh "{{ nodename }}" "{{ credid }}" "{{ label }}"
