---
- hosts: jenkins
  become: true
  tasks:

    - name: Change the password of the jenkins user
      ansible.builtin.user:
        name: jenkins
        update_password: always
        password: "{{ password|password_hash('sha512') }}"
